name: Make
on:
  create:
    tags:
      - '*'

jobs:
  compile:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Compile
        run: make -C $GITHUB_WORKSPACE
      - name: Publish
        uses: softprops/action-gh-release@v1
        with:
          files: |
            libssockets.so
            pub/ssockets.h
  docker:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Build and push Docker image
        uses: jlxip/docker-semver@1.0.0
        with:
          context: .
          image: jlxip/ssockets
          version: ${{ github.ref_name }}
